export const ErrorMessage = {
  ACCESS_DENIED: 'ACCESS_DENIED',
  TOKEN_NOT_FOUND: 'TOKEN_NOT_FOUND',
  INVALID_TOKEN: 'INVALID_TOKEN',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_DUPLICATE: 'RESOURCE_DUPLICATE',
  INVALID_BODY: 'INVALID_BODY',
};
