export enum Environment {
  DEVELOPMENT = 'development',
  PRODUCTION = 'production',
}

export enum EnvironmentVariable {
  NODE_ENV = 'NODE_ENV',
  CONTEXT_PATH = 'CONTEXT_PATH',
  FIREBASE_PROJECT_ID = 'FIREBASE_PROJECT_ID',
  FIREBASE_CLIENT_EMAIL = 'FIREBASE_CLIENT_EMAIL',
  FIREBASE_PRIVATE_KEY = 'FIREBASE_PRIVATE_KEY',
  MONGO_URI = 'MONGO_URI',
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
}
